buildscript {
    ext.kotlin_version = '1.9.0' 
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.4.0'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

gradle.projectsEvaluated {
    def newBuildDir = new File(rootProject.projectDir, '../build')
    rootProject.buildDir = newBuildDir

    subprojects.each { subproject ->
        def subBuildDir = new File(newBuildDir, subproject.name)
        subproject.buildDir = subBuildDir
    }
}

subprojects {
    evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.layout.buildDirectory
}
