// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6CZ84OcKbEwMOmVyd_gK756CxK1E9qko',
    appId: '1:874034750369:web:391d728365f7388ed261e0',
    messagingSenderId: '874034750369',
    projectId: 'aiapp-a1c07',
    authDomain: 'aiapp-a1c07.firebaseapp.com',
    storageBucket: 'aiapp-a1c07.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdBC6caa6MeJRE7RUeyKYtjo_SaNF3JEs',
    appId: '1:874034750369:android:16d44f2bcfbe668fd261e0',
    messagingSenderId: '874034750369',
    projectId: 'aiapp-a1c07',
    storageBucket: 'aiapp-a1c07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTS1ldyljLjzPiPqlXGijj3bJFpg-dRTY',
    appId: '1:874034750369:ios:535b625396c0474ed261e0',
    messagingSenderId: '874034750369',
    projectId: 'aiapp-a1c07',
    storageBucket: 'aiapp-a1c07.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTS1ldyljLjzPiPqlXGijj3bJFpg-dRTY',
    appId: '1:874034750369:ios:535b625396c0474ed261e0',
    messagingSenderId: '874034750369',
    projectId: 'aiapp-a1c07',
    storageBucket: 'aiapp-a1c07.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6CZ84OcKbEwMOmVyd_gK756CxK1E9qko',
    appId: '1:874034750369:web:b0b2052191ec932ed261e0',
    messagingSenderId: '874034750369',
    projectId: 'aiapp-a1c07',
    authDomain: 'aiapp-a1c07.firebaseapp.com',
    storageBucket: 'aiapp-a1c07.firebasestorage.app',
  );
}
