// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTnH25PmLZFr7n4vbnV5YDT4UG5-EbXKI',
    appId: '1:888154542569:web:1390e26b09b26b55fa7b78',
    messagingSenderId: '888154542569',
    projectId: 'testing-cli-12bce',
    authDomain: 'testing-cli-12bce.firebaseapp.com',
    storageBucket: 'testing-cli-12bce.appspot.com',
    measurementId: 'G-E1G9C305P8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxdl-h0s6ZXt0-O8b-DA-ZMHFsJDoQP7I',
    appId: '1:888154542569:android:feec873991f1f21ffa7b78',
    messagingSenderId: '888154542569',
    projectId: 'testing-cli-12bce',
    storageBucket: 'testing-cli-12bce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5lzKSRINRqvOdMxwGvsoFPD6xhGshByk',
    appId: '1:888154542569:ios:f6ce5c4895fa1070fa7b78',
    messagingSenderId: '888154542569',
    projectId: 'testing-cli-12bce',
    storageBucket: 'testing-cli-12bce.appspot.com',
    iosBundleId: 'com.example.demoProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5lzKSRINRqvOdMxwGvsoFPD6xhGshByk',
    appId: '1:888154542569:ios:f6ce5c4895fa1070fa7b78',
    messagingSenderId: '888154542569',
    projectId: 'testing-cli-12bce',
    storageBucket: 'testing-cli-12bce.appspot.com',
    iosBundleId: 'com.example.demoProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTnH25PmLZFr7n4vbnV5YDT4UG5-EbXKI',
    appId: '1:888154542569:web:44c4c55ea2b15f65fa7b78',
    messagingSenderId: '888154542569',
    projectId: 'testing-cli-12bce',
    authDomain: 'testing-cli-12bce.firebaseapp.com',
    storageBucket: 'testing-cli-12bce.appspot.com',
    measurementId: 'G-WM308BBJ7D',
  );
}
