// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdzR8wHY11UolkOfBPY4Fy7Ryn_f7VjNE',
    appId: '1:315352760568:web:0a05d1b2185795585afb0d',
    messagingSenderId: '315352760568',
    projectId: 'fir-eec07',
    authDomain: 'fir-eec07.firebaseapp.com',
    storageBucket: 'fir-eec07.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqDuLZt-Ai0Zu17N9gml78H8ehkHfqxgA',
    appId: '1:315352760568:android:c069c47f3039be4c5afb0d',
    messagingSenderId: '315352760568',
    projectId: 'fir-eec07',
    storageBucket: 'fir-eec07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-WFYuySUEqb8zexoTPOcAL_WpkqgFpus',
    appId: '1:315352760568:ios:cbac1d23ed6813cc5afb0d',
    messagingSenderId: '315352760568',
    projectId: 'fir-eec07',
    storageBucket: 'fir-eec07.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-WFYuySUEqb8zexoTPOcAL_WpkqgFpus',
    appId: '1:315352760568:ios:cbac1d23ed6813cc5afb0d',
    messagingSenderId: '315352760568',
    projectId: 'fir-eec07',
    storageBucket: 'fir-eec07.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdzR8wHY11UolkOfBPY4Fy7Ryn_f7VjNE',
    appId: '1:315352760568:web:207b640f91a0540c5afb0d',
    messagingSenderId: '315352760568',
    projectId: 'fir-eec07',
    authDomain: 'fir-eec07.firebaseapp.com',
    storageBucket: 'fir-eec07.firebasestorage.app',
  );
}
